### ISSUE TITLE
Allow custom GPIO initialization in DeviceSelector

### ISSUE THREAD

**Issue by valoni** [ghi-electronics/TinyCLR-Ports#23]
on **DeviceSelector.h** maybe is good to add an option for pins pullup/pulldown declaration for default values (to be included on compile/creation of firmware)

Gpio pins state (pullup,pulldown) declaration of default values states for pins

 **for example:**

_p(a,0) = 1 or _p(a,0) = 0 or _p(a,0)=-1 which will activate (pullup, none, pulldown) or different way
_p(a,0) = u or _p(a,0) = n or _p(a,0)=d

**Comment by Arke64** [comment]
Something like this is possible. We can do it like we do with PWM where we provide some initialization values. Not just pull mode, also drive mode and any other parameters that GPIO on the processor supports.
