### ISSUE TITLE
Investigate if we want to define display backlight in native

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Ports#309]

**Comment by Palomino34** [comment]
Backlight is not a part of LCD controller so it shouldn't be in native, I think.

**Comment by Arke64** [comment]
There should be parallels here with the SD card detect pin. Maybe expose backlight as a get/set on the display controller, it could return not supported. But the user may want to PWM it, so maybe not.

**Comment by Arke64** [comment]
We do not. It will be part of the display driver object we provide ghi-electronics/TinyCLR-Drivers#12
