### ISSUE TITLE
G30 overloaded size if add SD and FileSystem

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#322]
Currently 11.7KB overload if add SD and FileSystem

**Comment by Palomino34** [comment]
Size is fit to 225K now.

**Comment by Palomino34** [comment]
Implement some more functions and it is oversize again!

**Comment by Arke64** [comment]
When adding signals we're over again

**Comment by Arke64** [comment]
Fixed in #454 ghi-electronics/TinyCLR-Devices#301 and ghi-electronics/TinyCLR-Devices#302
