### ISSUE TITLE
FileSystem: GetDirectories() always throws exception

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#343]
https://forums.ghielectronics.com/t/sdcard-problem/21541/

**Comment by Palomino34** [comment]
GetFiles() also has same issue.

**Comment by Arke64** [comment]
Fixed in ghi-electronics/TinyCLR-Libraries#263 and ghi-electronics/TinyCLR-Devices#291

**Comment by Palomino34** [comment]
Need test more. We didn't test folder/files in folder yet.

**Comment by Palomino34** [comment]
Tested and works
