### ISSUE TITLE
Finish implementing signal interop

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#357]
Stop implement interop, switch to filesystem to update from "clean" branch

Scheduled Implementing Signal interop for next thing.

- [ ] Signal Generator
- [ ] Signal Capture
- [ ] Pulse Feedback

**Comment by Arke64** [comment]
I did some basic work for generator and capture, but not all of the properties are used. PulseFeedback does nothing.
