### ISSUE TITLE
Implement new storage provider interop

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#358]
GHIElectronics_TinyCLR_Devices_GHIElectronics_TinyCLR_Devices_SdCard_Provider_SdCardControllerApiWrapper.cpp

function GetSectorMap, line 109, need to create an array? Let test to see.

**Comment by Arke64** [comment]
SD card was turned into a generic storage provider. GetSectorMap was turned into a GetDescriptor function which returns a new object, which has arrays inside of it.

**Comment by Arke64** [comment]
All have been implemented.
