### ISSUE TITLE
Acquire and release should work with being called multiple times

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Ports#397]
Acquire increments an internal counter, only initializing everything the first time. Release decements the counter, releaseing everything when zero. aka reference counting.

**Comment by Arke64** [comment]
ADC, CAN, DAC, Display, GPIO, I2C, PWM, RTC, SPI, Storage, UART, USBC

**Comment by Palomino34** [comment]
Fixed.
