### ISSUE TITLE
UART doesn't work on FEZ.

### ISSUE THREAD

**Issue by JoelGHI** [ghi-electronics/TinyCLR-Ports#413]
Same UART loop back test that works on G80 does not work on FEZ. Could not detect any data being transmitted on TX pin. It appears that the TX pin idle state is low when it should be high. Also, could not receive data on FEZ RX pin sent from G80 TX pin.

**Comment by Arke64** [comment]
D0 and D1 UART that is

**Comment by Palomino34** [comment]
is it only happened when receiving a lot of data? Duplicate #411 ?

**Comment by Palomino34** [comment]
Double check on 2 FEZ, works fine. Probably was connection issue.
