### ISSUE TITLE
Servo on BrainPad doesn't work

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Ports#414]
Appears to be something with the ordering of PWM calls

[Program.zip](https://github.com/ghi-electronics/TinyCLR-Ports/files/2298570/Program.zip)

**Comment by JoelGHI** [comment]
On FEZ cannot get two PWM channels working properly when they are using the same controller -- only one works properly. When I switch one channel to a different controller, both channels work.
