### ISSUE TITLE
Debugging in VS sometimes pauses forever until you manually break

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#42]
With VS debug attached, sometime the application pause at a line forever ,usually Thread.sleep(x). Some interrupt can wake the system up and continue running.

If stop VS, using TinyCLR Config, we can connect, ping... do everything, meaning the system does not crashed, just don't run next line that it should be.

A little hard to reproduce, but about 25% in EMX and more in smaller version like USBizi.

**Comment by Arke64** [comment]
It's enough to sit in a loop and hold down F10, locks up after about a minute.

```cs            
while (true) {
    Thread.Sleep(10);
}
```
