### ISSUE TITLE
Debugging in VS with USBizi crashes the firmware sometimes

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#43]
Unlike PORT #42, this is crashed issue without any reason when VS attached. 
Only happen in USBizi

fragment memory ?

**Comment by Palomino34** [comment]
Frequency about 40-50%

**Comment by Arke64** [comment]
Possibly also with EMX https://forums.ghielectronics.com/t/fez-spider-with-blinky-app-bug

**Comment by Palomino34** [comment]
Fixed by ghi-electronics/TinyCLR-Core#246

**Comment by Palomino34** [comment]
Fixed by ghi-electronics/TinyCLR-Core#246

For issue: https://forums.ghielectronics.com/t/fez-spider-with-blinky-app-bug, could not reproduce after 0.9.0
