### ISSUE TITLE
Tiny CLR Config

### ISSUE THREAD

**Issue by PRIMETSS** [ghi-electronics/TinyCLR-Ports#463]
Not a big issue, but is it possible to have an 'About' page on TinyCLR Config displaying its installed version.
As when installing the .msi it happens so fast with no notification and every time I update it, I do it twice or more just to make sure its the latest version.
But there is no way to check what version it is as far as I can see....

**Comment by Arke64** [comment]
Thanks for the suggestion, we'll add a version to the UI in a future release (not 1.0 though since we're on the road to RTW now). Closing this since it's tracked in another internal repo.

Moved to ghi-electronics/TinyCLR-Config#24
