### ISSUE TITLE
G120E: "Cannot find any entrypoint"

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#520]
Not found on G120 but easy to be happened on G120E

![image](https://user-images.githubusercontent.com/15822304/47461518-f9cc5780-d7ae-11e8-96ca-8cd36f8836e2.png)

**Comment by Palomino34** [comment]
To reproduce issue, easy way is tied pin P3_30 to GND, accessing SDRAM seems failed that cause CRC wrong.

Another way to reproduce by code is:
```
static void Main()
        {
            var p3_30 = GpioController.GetDefault().OpenPin(3 * 32 + 30);

            p3_30.SetDriveMode(GpioPinDriveMode.InputPullDown);
  
            var counter = 0U;
            while (true)
            {
                Thread.Sleep(500);

                System.Diagnostics.Debug.WriteLine("System is running...." + counter++);
            }

        }
```

**Comment by Arke64** [comment]
While it doesn't take care of the root issue, we probably want to change all GPIO on all devices to be no-init. The processor defaults should be enough.

**Comment by Arke64** [comment]
Folded into #564
