### ISSUE TITLE
Signal Generator value is incorrect some cases.

### ISSUE THREAD

**Issue by Palomino34** [ghi-electronics/TinyCLR-Ports#526]
```var buffer = new[] {
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(3),
            TimeSpan.FromMilliseconds(4),
            TimeSpan.FromMilliseconds(5),
            TimeSpan.FromMilliseconds(6),
            TimeSpan.FromMilliseconds(7),
        };
```

give values 2400, 2800, 4000, 5200, 6000, 6800, on scope
But 

 ```var buffer = new[] {
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(2),
            TimeSpan.FromMilliseconds(2),
        };
```

scope shows correctly.

**Comment by Palomino34** [comment]
The issue now only found on G120 and G400.
With the zip attach file, G400 will work more accurate, but won't apply to official build for
[AT91SAM9X35_ReWriteILoopDelay.zip](https://github.com/ghi-electronics/TinyCLR-Ports/files/2536366/AT91SAM9X35_ReWriteILoopDelay.zip)
 now.

**Comment by Palomino34** [comment]
Close because comment above.

**Comment by Arke64** [comment]
We will look into a fix, just not for preview 3.

**Comment by Palomino34** [comment]
In Preview3: Not found on G120E, but found on all STM and G400
