### ISSUE TITLE
Fix CAN timing.

### ISSUE THREAD

**Issue by JoelGHI** [ghi-electronics/TinyCLR-Ports#576]
In STM32F4_CAN.cpp Propagation is ignored.

In LPC17_CAN.cpp Propagation, SJW, and UseMultiBitSampling are ignored.

In AT91SAM9X35_CAN.cpp Propagation, Phase1, Phase2, BaudratePrescaler, and SJW must all have one subtracted before saving to registers.

In STM32F7_CAN.cpp Propagation is ignored.

**Comment by JoelGHI** [comment]
LPC24_CAN.cpp also ignores Propagation, SJW, and UseMultiBitSampling.

**Comment by Arke64** [comment]
Once we review this, review and update the sample timings in docs
