### ISSUE TITLE
LPC23xx-LPC24xx:  LPC24_Flash_GetPartId defined twice

### ISSUE THREAD

**Issue by dobova86** [ghi-electronics/TinyCLR-Ports#623]
Compiling EMX firmware v.1.0.0 the ld find double definition for 

> uint32_t LPC24_Flash_GetPartId()

function. I found that It is defined in both LPC24_Flash.cpp and LPC24_Deployment.cpp.

**Comment by Palomino34** [comment]
Do we have LPC24_Flash.cpp file? You may need to clean up folder.
