### ISSUE TITLE
Errors Building TinyCLR Build For WifiMCU ERRORS AND SOLUTION

### ISSUE THREAD

**Issue by ajaybnl** [ghi-electronics/TinyCLR-Ports#625]
The Errors and non compiled Due to Device.h Missing Variables (For WifiMCU) 
Errors in build:

_STM32F4_I2C.cpp:25:46: error: 'STM32F4_I2C_PINS' was not declared in this scope
STM32F4_SPI.cpp:33:46: error: 'STM32F4_SPI_PINS' was not declared in this scope
STM32F4_UART.cpp:75:47: error: 'STM32F4_UART_PINS' was not declared in this scope
STM32F4_UsbDevice.cpp:245:52: error: 'STM32F4_USB_PINS' was not declared in this scope_

**Sucessfully Build by adding these lines** in TinyCLR\Devices\WifiMcu\Device.h : 

These Pins are Copied from the same board file (differnt variables was written previously)
The build firmware will not have any problem.

> 
> //ADDED
> //#####################################################################
> #define STM32F4_I2C_PINS {/*            SDA                   SCL*/               \
>                           /*I2C0*/  { { PIN(B, 9), AF(4) }, { PIN(B, 8), AF(4) } }\
>                          }
> 
> #define STM32F4_SPI_PINS {/*         MOSI                    MISO                   CLOCK*/                \
>                           /*SPI0*/{ { PIN(A,  7), AF(5) },  { PIN(A,  6), AF(5) }, { PIN(A, 5) , AF(5) } },\
>                           /*SPI1*/{ { PIN(B, 5), AF(5) },  { PIN(B, 4), AF(5) }, { PIN(B, 3), AF(5) } } \
>                          }
> 						 
> #define STM32F4_UART_PINS {/*           TX                       RX                      RTS                       CTS*/                   \
>                            /*UART0*/{ { PIN(B,  6), AF(7)   }, { PIN(A, 10), AF(7)   }, { PIN_NONE  , AF_NONE }, { PIN_NONE  , AF_NONE } },\
>                            /*UART1*/{ { PIN(A, 2), AF(7)    }, { PIN(A, 3), AF(7)    }, { PIN_NONE , AF_NONE    }, { PIN_NONE , AF_NONE    } } \
>                            }						 
> 						 
> #define STM32F4_USB_PINS {/*           DM                      DP                      VB                      ID*/                  \
>                           /*USBC0*/{ { PIN(A, 11), AF(10) }, { PIN(A, 12), AF(10) }, { PIN(A,  9), AF(10) }, { PIN(A, 10), AF(10) } }\
>                          }
> 						 
> 						 
> //#####################################################################
>

**Comment by Arke64** [comment]
This isn't a port officially maintained by us, so we don't have any fixes forthcoming. But if you want to have a go at it yourself, I would start off with comparing it to the same file on the FEZ: https://github.com/ghi-electronics/TinyCLR-Ports/blob/master/Devices/FEZCLR/Device.h

Also, make sure you are working with files from the `master` branch, not the default `dev` branch.
