### ISSUE TITLE
How big is Tiny CLR?

### ISSUE THREAD

**Issue by The-Futurist** [ghi-electronics/TinyCLR-Ports#632]
Approx how much memory does Tiny CLR take up when installed with a running app? How big could it grow to (if features were added) before size became a serious problem for the devices it currently targets?

Is there any document or details about a typical memory map when a C# app is loaded and running? Just to get an idea of the bits n pieces that are needed and their approx size.

**Comment by Arke64** [comment]
There isn't really a good number we can give at the moment. We're currently hard at work on the next version and a lot of features are being added, so the size is in flux.  As we get closer to that release we can certainly release some size numbers.

For a rough estimate that can change: For a firmware with all features in it, expect it to be in the range of 1-4MB. RAM usage will depend on what your app does but a good minimum is 50-100KB. On top of all of that add your actual application.
