### ISSUE TITLE
couldn't add more SPI  @ NUCLEO-F411RE

### ISSUE THREAD

**Issue by valoni** [ghi-electronics/TinyCLR-Ports#68]
can not add more SPI on Nucleo 

i make example with G80 could add without problem
but NUCLEO-F411RE fail compile 

i belive it was problem probably need to use STM32F411xE  instead STM32F401xE

**Comment by Arke64** [comment]
With the update to the latest DeviceSelector.h format in dev, you can now add more SPIs. See also #67.
