### ISSUE TITLE
Update and verify device peripheral mapping

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Ports#9]
Make sure the mapping is correct. Some devices will likely only need verification, like G30. Others, like, Cerb will need to be updated.

- [x] FEZCLR
- [x] G30
- [x] G80
- [x] Cerb
- [x] G120
- [x] G120E
- [x] EMX
- [x] Embedded Master
- [ ] Embedded Master non-TFT
- [ ] USBizi100
- [ ] USBizi144
- [ ] G400S
- [ ] G400D
- [ ] ChipworkX
- [x] FEZ Hydra
- [ ] netduino3
- [ ] Quail
- [ ] clicker
- [ ] clicker2
- [ ] Due

**Comment by Arke64** [comment]
Cerb pins has four uarts, firmware only has two. We need to add the remaining two to the firmware, make sure the mapping is correct and not the NETMF mapping.

**Comment by Palomino34** [comment]
G30, G80, G120/G120E, EMX, G400,Cerberus, EMM, USBizi, FEZHydra, FEZCLR peripheral mapping are correct.

**Comment by Arke64** [comment]
Reopening to do the rest. For Usbizi and G400, we want to see if we want to split up the mappings for each of the two devices the firmwares run on.

**Comment by Arke64** [comment]
Duplicate of ghi-electronics/TinyCLR-Devices#123
